# ==============================================================================
# 12_realized_benefit.R — Realised benefit per sub-basin (provision × demand)
# ------------------------------------------------------------------------------
# For each scenario (one folder under data/processed/runoff/):
#
#   1. Aggregate PRR (mm·km²) per sub-basin. PRR is intrinsically zero on
#      non-natural pixels (their CN does not change between scenarios), so a
#      raw raster sum already isolates natural-ecosystem retention.
#
#   2. natural_km2_j  = Σ pixels (natural_mask × pixel_area) per sub-basin.
#   3. PRR_per_NAT_j  = PRR_total_j / natural_km2_j   (mm).
#   4. RI_j           = PRR_per_NAT_j × TDA_j         (provision × demand).
#
#   5. Apply Duarte's ranking filter (`05_realized_benefits/02_*`):
#         natural_km2 > 0  ∧  current runoff > 0  ∧  TDA > 0
#      Only eligible sub-basins enter the percentile cut; ineligible rows are
#      kept in the GPKG with `rank_eligible = FALSE`, `ri_interval = NA`.
#   6. Cut RI into Duarte's percentile intervals
#      {0–25, 25–50, 50–60, 60–70, 70–80, 80–85, 85–90, 90–95, 95–100}.
#   7. Outliers (PRR_per_NAT > mean + 3·SD) are capped. NOTE: Duarte only
#      *computed* mean + 3·SD as a diagnostic (04_evaluating_spa_prr/01) and
#      reported it; they did not cap the values before binning. Capping here is
#      a deliberate choice to stop a few extreme natural sub-basins from
#      stretching the upper percentile breaks — it changes top-bin membership
#      relative to a verbatim Duarte run, so flag it if reproducing their table.
#
# Two outcome views:
#   _all      — every provider sub-basin (used for honest cross-jurisdiction ranking)
#   _outcome  — filtered to in_outcome_aoi == TRUE (the MVRD ∪ FVRD deliverable)
#
# Inputs (data/processed/):
#   runoff/<scenario>/09_prr_mm.tif
#   03_lulc_natural_mask.tif
#   02_subbasins.gpkg
#   11_tda_subbasin.gpkg
#
# Outputs (data/processed/):
#   12_realised_benefit_<scenario>_all.gpkg
#   12_realised_benefit_<scenario>_outcome.gpkg
# ==============================================================================

source(here::here("R", "00_setup.R"))

INTERVAL_QUANTILES <- c(0, 0.25, 0.50, 0.60, 0.70, 0.80, 0.85, 0.90, 0.95, 1.00)
INTERVAL_LABELS <- c("0_25","25_50","50_60","60_70","70_80","80_85","85_90","90_95","95_100")

sb <- sf::st_read(file.path(paths()$processed, "02_subbasins.gpkg"), quiet = TRUE)
tda <- sf::st_read(file.path(paths()$processed, "11_tda_subbasin.gpkg"), quiet = TRUE) |>
  sf::st_drop_geometry()
nat_mask <- terra::rast(file.path(paths()$processed, "03_lulc_natural_mask.tif"))

# natural area per sub-basin (km²) = natural-pixel count × constant pixel area
px_km2 <- (terra::xres(nat_mask) * terra::yres(nat_mask)) * 1e-6
sb$natural_km2 <- px_km2 * exactextractr::exact_extract(nat_mask, sb, "sum")

# Current-LULC runoff per sub-basin (mm·km^2)
# screen sub-basins with zero runoff at the ranking step
scenarios <- list.dirs(file.path(paths()$processed, "runoff"),
                       recursive = FALSE, full.names = TRUE)
scenarios <- scenarios[basename(scenarios) != "runoff"]

for (scen_dir in scenarios) {
  scen <- basename(scen_dir)
  prr  <- terra::rast(file.path(scen_dir, "09_prr_mm.tif"))
  q_b  <- terra::rast(file.path(scen_dir, "09_q_baseline_mm.tif"))

  # PRR_total per sub-basin (mm·km² ≈ thousand m³) = raw raster sum × pixel area.
  # PRR is intrinsically zero on non-natural pixels (their CN does not change
  # between scenarios), so a raw sum already equals "PRR generated by natural
  # ecosystems in this sub-basin". Duarte's per-pixel `runoff_*_ben` mask was a
  # *sub-basin* filter via a hydrobasins rasterization — applied below, not here.
  prr_total <- px_km2 * exactextractr::exact_extract(prr, sb, "sum")
  q_b_total <- px_km2 * exactextractr::exact_extract(q_b, sb, "sum")

  # PRR per natural km² (provision intensity).
  prr_per_nat <- ifelse(sb$natural_km2 > 0, prr_total / sb$natural_km2, 0)

  # Outlier cap at mean + 3·SD over non-zero sub-basins. Duarte compute this
  # same threshold in 04_evaluating_spa_prr/01 but use it only as a reported
  # diagnostic; pmin() here actively clips to it (see header note). Stats are
  # over PRR-positive basins so empty basins don't drag the mean toward zero.
  m <- mean(prr_per_nat[prr_per_nat > 0], na.rm = TRUE)
  s <- sd(prr_per_nat[prr_per_nat > 0],   na.rm = TRUE)
  cap <- m + 3 * s
  prr_per_nat_capped <- pmin(prr_per_nat, cap)

  # Join TDA, compute RI = provision × demand.
  joined <- dplyr::left_join(
    dplyr::tibble(HYBAS_ID = sb$HYBAS_ID,
                  natural_km2 = sb$natural_km2,
                  q_baseline_mm_km2 = q_b_total,
                  prr_total_mm_km2 = prr_total,
                  prr_per_nat_mm_km2 = prr_per_nat_capped),
    tda |> dplyr::select(HYBAS_ID, dplyr::starts_with("tda_"), in_outcome_aoi),
    by = "HYBAS_ID"
  )
  joined$ri_index <- joined$prr_per_nat_mm_km2 * joined$tda_total_w

  # Duarte's ranking filter (`05_realized_benefits/02_basins_RItop5basins_critical.R`):
  # exclude sub-basins with no natural area, no current runoff, or no
  # downstream demand. Keep them in the output but mark them ineligible so
  # the percentile bins reflect only the providers that can move the needle.
  eligible <- joined$natural_km2 > 0 &
    joined$q_baseline_mm_km2 > 0 &
    joined$tda_total_w > 0 &
    is.finite(joined$ri_index)

  ri_for_cut <- ifelse(eligible, joined$ri_index, NA_real_)
  q <- stats::quantile(ri_for_cut, INTERVAL_QUANTILES, na.rm = TRUE)
  joined$ri_interval <- cut(ri_for_cut, breaks = q, labels = INTERVAL_LABELS,
                            include.lowest = TRUE)
  joined$rank_eligible <- eligible

  out_all <- sb |>
    dplyr::select(HYBAS_ID) |>
    dplyr::left_join(joined, by = "HYBAS_ID")

  f_all <- file.path(paths()$processed, glue::glue("12_realised_benefit_{scen}_all.gpkg"))
  sf::st_write(out_all, f_all, delete_dsn = TRUE, quiet = TRUE)

  out_outcome <- dplyr::filter(out_all, in_outcome_aoi)
  f_outcome   <- file.path(paths()$processed,
                           glue::glue("12_realised_benefit_{scen}_outcome.gpkg"))
  sf::st_write(out_outcome, f_outcome, delete_dsn = TRUE, quiet = TRUE)

  # ---- QA preview ------------------------------------------------------------
  # Headline output: percentile bins of RI across eligible providers, with the
  # MVRD ∪ FVRD outline overlaid so the "providers that move the needle for
  # the Lower Mainland" subset is visually obvious.
  qa_png(paste0("12_ri_interval_", scen, ".png"), function() {
    op <- graphics::par(mar = c(2, 2, 3, 1))
    on.exit(graphics::par(op), add = TRUE)
    out_plot <- out_all
    out_plot$ri_interval <- factor(as.character(out_plot$ri_interval),
                                   levels = INTERVAL_LABELS, ordered = TRUE)
    plot(out_plot["ri_interval"],
         main = paste0("Realised-benefit percentile interval — ", scen),
         border = "grey60", lwd = 0.2, key.pos = 4,
         pal = grDevices::hcl.colors(length(INTERVAL_LABELS),
                                     palette = "YlGnBu", rev = TRUE),
         reset = FALSE)
    outcome_aoi <- read_aoi("outcome")
    plot(sf::st_geometry(outcome_aoi), add = TRUE, border = "red", lwd = 1.2)
  })

  message("  ✓ scenario '", scen, "' → realised benefit + intervals written")
}

message("✓ 12_realized_benefit.R — completed ", length(scenarios), " scenario(s)")